workflows:
  test-workflow:
    name: Test osv-scanner
    max_build_duration: 60
    environment:   
      flutter: 3.35.0
    scripts:
      - name: Get dependencies
        script: |
          echo "Get dependencies"
          flutter packages pub get    
      - name: Run osv scanner
        script: |
          chmod +x ci_scripts/script.sh
          ./ci_scripts/script.sh
    publishing:
      email:
        recipients:
          - tmovlian@gmail.com          
          - tetiana.movlian@solid.software
  flutter_tests_pr:
    name: Flutter tests (Pull Requests)
    max_build_duration: 60
    environment:   
      flutter: 3.35.0
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: false 
      scripts:
        - name: Get dependencies
          script: |
            echo "Get dependencies"
            flutter packages pub get 
        - name: Run code generation
          script: |
            flutter pub run build_runner build --delete-conflicting-outputs
        - name: Run Flutter tests
          script: flutter test --coverage